# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2c359050fdb50d3982ff68362af8e700"
name = "EnquireIt"
application_url = "https://enquireit-production.up.railway.app/app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "byticslab-2.myshopify.com"

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://enquireit-production.up.railway.app/auth/callback",
  "https://enquireit-production.up.railway.app/auth/shopify/callback",
  "https://enquireit-production.up.railway.app/api/auth/callback"
]

[pos]
embedded = false
