api_version = "2024-04"

[[extensions]]
uid = "6e58d605-26e5-b267-62dc-990d57a9be42660f6d6a"
type = "theme"
name = "Enquiry Modal"
handle = "enquiry-modal"

  [extensions.development]
    preview_url = "/"
